# Maestro Configuration
# See: https://maestro.mobile.dev/

appId: com.sidebet.app

# Environment variables for tests
env:
  TEST_USER_EMAIL: "testuser@sidebet.test"
  TEST_USER_PASSWORD: "TestPassword123!"
  TEST_ADMIN_EMAIL: "testadmin@sidebet.test"
  TEST_ADMIN_PASSWORD: "AdminPassword123!"

# Increase timeout for slow operations
commandTimeout: 30000

# Take screenshots on failure
screenshotOnFailure: true

# Retry failed tests
retries: 1
